title: "ペタパンポートフォリオ"
# email: wowthemesnet@gmail.com
timezone: Tokyo
baseurl: ""
permalink: "/:title/"
logo: 'assets/images/logo.png'
favicon: 'assets/images/pancake_icon.ico'
author: Sal
paginate: 30
disqus: 'demowebsite'
locale: ja_JP
og_image: /assets/images/ogp/default.png
lang: ja_jp
feed_items: 10
feed_update_period: daily
feed_update_frequency: 1
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true
sass:
  sass_dir: _sass
  style: :compressed
ganalytics: 

# Authors
authors:
  sal:
    name: ペタパン
    display_name: ペタパン
    avatar: 'assets\images\petapan.png'
    web: https://kairi1091.github.io/
    description: "Author of Affiliates, a template available for WordPress, HTML, Ghost and Jekyll. You are currently previewing Jekyll template demo."

# Social
# social:
#   instagram: https://www.instagram.com/bootstrapstarter/
#   facebook: https://www.facebook.com/bootstrapstartercom-346329609045284
#   twitter: https://twitter.com/bstartercom

# Plugins
plugins: 
- jekyll-paginate
- jekyll-sitemap
- jekyll-feed
- jekyll-seo-tag
- jekyll-archives

destination: _site
google-site-verification: c8UmFJQ-qsAgjXBoVtf13N2Qnf2hZzIrVz5ikNWNr60